[[exhentai]]
domain = '.exhentai.org'
expirationDate = 1499182195
hostOnly = false
httpOnly = false
name = '__utma'
path = '/'
secure = false
session = false
storeId = '0'
value = '185428086.1346077875.1436109738.1436109738.1436109738.1'
id = 1

[[exhentai]]
domain = '.exhentai.org'
expirationDate = 1436111995
hostOnly = false
httpOnly = false
name = '__utmb'
path = '/'
secure = false
session = false
storeId = '0'
value = '185428086.5.10.1436109738'
id = 2

[[exhentai]]
domain = '.exhentai.org'
hostOnly = false
httpOnly = false
name = '__utmc'
path = '/'
secure = false
session = true
storeId = '0'
value = '185428086'
id = 3

[[exhentai]]
domain = '.exhentai.org'
expirationDate = 1436110338
hostOnly = false
httpOnly = false
name = '__utmt'
path = '/'
secure = false
session = false
storeId = '0'
value = '1'
id = 4

[[exhentai]]
domain = '.exhentai.org'
expirationDate = 1451878195
hostOnly = false
httpOnly = false
name = '__utmz'
path = '/'
secure = false
session = false
storeId = '0'
value = '185428086.1436109738.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
id = 5

[[exhentai]]
domain = '.exhentai.org'
expirationDate = 1467646195.618398
hostOnly = false
httpOnly = false
name = 'event'
path = '/'
secure = false
session = false
storeId = '0'
value = '1'
id = 6

[[exhentai]]
domain = '.exhentai.org'
expirationDate = 1467646088.955735
hostOnly = false
httpOnly = false
name = 'ipb_member_id'
path = '/'
secure = false
session = false
storeId = '0'
value = '2432523'
id = 7

[[exhentai]]
domain = '.exhentai.org'
expirationDate = 1467646088.955736
hostOnly = false
httpOnly = false
name = 'ipb_pass_hash'
path = '/'
secure = false
session = false
storeId = '0'
value = 'fe20c5cd028d95ae583ed1f8385b25f0'
id = 8

[[exhentai]]
domain = '.exhentai.org'
hostOnly = false
httpOnly = false
name = 'ipb_session_id'
path = '/'
secure = false
session = true
storeId = '0'
value = '81a2f8ffca8439f9d31f8e10d6dbf446'
id = 9
