version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/memo

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/memo

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm install
      - run:
          command: |
            set +eo
            npm ls
            true
      - persist_to_workspace:
          root: ~/memo
          paths:
            - node_modules
  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run codecov
      - run: bash <(curl -s https://codecov.io/bash) -t b0824134-3eef-4895-8b64-95d258ac57aa
  dist:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: dist
          when: on_success
          command: npm run build
      - persist_to_workspace:
          root: ~/memo
          paths:
            - dist
  deploy:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - add_ssh_keys:
          fingerprints:
            - '6b:38:b8:ae:87:df:d9:4f:99:fe:96:ee:f9:64:fe:05'
      - run:
          name: deploy
          when: on_success
          command: npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - dist:
          requires:
            - test
      - deploy:
          requires:
            - dist
          filters:
            branches:
              only: master
